# Models
GUILD_NAME_MAX_LENGTH = 100
CHARACTER_MAX_LENGTH = 256
EVENT_NAME_MAX_LENGTH = 50
IS_ACTIVE_MAX_LENGTH = 50

# website DKP
HOME_URL = 'dkp:home'
AUCTION_URL = 'dkp:auction'
DKP_OBJECTS_ON_PAGE = 20
LOT_OBJECTS_ON_PAGE = 3
