# Generated by Django 3.2.3 on 2024-10-30 08:53

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_image', models.ImageField(upload_to='auctions/', verbose_name='Изображение лота')),
                ('close_date', models.DateTimeField(validators=[core.validators.validate_close_date_greater_than_created_at], verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.CharField(choices=[('active', 'Активный'), ('closed', 'Завершенный')], default='active', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'аукцион',
                'verbose_name_plural': 'Аукционы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.IntegerField(verbose_name='Ставка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Имя персонажа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
                ('is_active', models.CharField(choices=[('active', 'Активный'), ('closed', 'Завершенный')], default='active', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'События',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('cost', models.IntegerField(validators=[core.validators.validate_greater_than_zero], verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название гильдии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'гильдия',
                'verbose_name_plural': 'Гильдии',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EventCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_character', to='dkp.character', verbose_name='Персонаж')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='dkp.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'регистация в собитии',
                'verbose_name_plural': 'Регистация в собитии',
                'ordering': ('event_id',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type', to='dkp.eventtype', verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='Dkp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очки дкп')),
                ('last_activity', models.DateTimeField(verbose_name='Дата последней активности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный аккаунт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkp_character', to='dkp.character', verbose_name='Имя персонажа')),
            ],
            options={
                'verbose_name': 'DKP',
                'verbose_name_plural': 'DKP',
                'ordering': ('user',),
            },
        ),
    ]
