# Generated by Django 3.2.3 on 2024-11-25 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dkp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dkp',
            options={'ordering': ('character__name',), 'verbose_name': 'DKP', 'verbose_name_plural': 'DKP'},
        ),
        migrations.AlterField(
            model_name='bet',
            name='auction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='dkp.auction', verbose_name='Аукцион'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_characters', to='dkp.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_characters', to='dkp.guild', verbose_name='Гильдия'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dkp',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkp_characters', to='dkp.character', verbose_name='Имя персонажа'),
        ),
        migrations.AlterField(
            model_name='dkp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dkp_users', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='dkp.eventtype', verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='eventcharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_characters', to='dkp.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='eventcharacter',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dkp.event', verbose_name='Событие'),
        ),
    ]
