# Generated by Django 3.2.3 on 2024-11-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0003_auto_20241125_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='close_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_characters', to='dkp.guild', verbose_name='Гильдия'),
        ),
        migrations.AlterField(
            model_name='dkp',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkp_characters', to='dkp.character', verbose_name='Имя персонажа'),
        ),
    ]
